# Generated by Django 3.2.12 on 2022-04-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_event', models.DateField()),
                ('date_insert', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Миникап', 'Mini'), ('Клубные игры', 'Fun')], default='Клубные игры', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.CharField(choices=[('Победа черных', 'Black'), ('Победа красных', 'Red')], default='Победа красных', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mafia.event')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Красный', 'User'), ('Шериф', 'Admin'), ('Черный', 'Black')], default='Красный', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('role', models.CharField(choices=[('Красный', 'Citizen'), ('Шериф', 'Sheriff'), ('Мафия', 'Mafia'), ('Дон', 'Don')], default='Красный', max_length=20)),
                ('best_move', models.CharField(default='none', max_length=20)),
                ('add_point', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mafia.game')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mafia.people')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mafia.people'),
        ),
    ]
