# Generated by Django 3.2.12 on 2022-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mafia', '0003_alter_player_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FUN', 'Клубные игры'), ('MINI', 'Миникап')], default='FUN', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='win',
            field=models.CharField(choices=[('BLACK', 'Победа черных'), ('RED', 'Победа красных'), ('NONE', 'Нет результата')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Красный'), ('SHERIFF', 'Шериф'), ('MAFIA', 'Мафия'), ('DON', 'Дон')], default='CITIZEN', max_length=20),
        ),
    ]
