# Generated by Django 3.2.12 on 2022-04-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mafia', '0007_alter_player_add_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='add_point',
            field=models.FloatField(choices=[(-0.5, -0.5), (0, 0), (0.1, 0.1), (0.2, 0.2), (0.25, 0.25), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7)], default=0),
        ),
    ]
